#! /usr/bin/env python
import os
import sys
import argparse
from slackclient import SlackClient

slack_token = os.getenv("SLACK_TOKEN")

if slack_token == None:
    print("Please set the SLACK_TOKEN env variable")
    sys.exit(1)

parser = argparse.ArgumentParser(description="Send a slack notification")
parser.add_argument("--channel", help="slack channel to send notification to", required=True)
parser.add_argument("--message", help="message to be send", required=True)
args = parser.parse_args()

sc = SlackClient(slack_token)
sc.api_call(
    "chat.postMessage",
    channel=args.channel,
    text = args.message
)
